### ISSUE TITLE
コラボレーターの設定について

### ISSUE THREAD

**Issue by hakobera-ss** [4ioskd/PDJF#2]
現在このプロジェクトに関わっている人数であれば、コラボレーターを複数人設定しなくても良いのではないかと思いますがいかがでしょうか？

**Comment by 4ioskd** [comment]
承知しました。コラボレーターの就任への招待を複数の人にお声掛けしてましたが、一旦全て取り下げました。

**Comment by hakobera-ss** [comment]
対応ありがとうございます。では解決済みとして本件はクローズします。
